# Useful verification commands actually used during the build.

sudo wwctl node list -a
sudo wwctl container list
sudo wwctl overlay build
sudo wwctl configure --all
sudo systemctl status slurmctld
sinfo
showmount -e localhost
sudo firewall-cmd --list-all
