# Overlay-related commands recorded in the build.

sudo mkdir -p /srv/warewulf/overlays/runtime/etc/munge/
sudo mkdir -p /srv/warewulf/overlays/runtime/etc/slurm/
sudo cp /etc/slurm/slurm.conf /srv/warewulf/overlays/runtime/etc/slurm/slurm.conf
sudo wwctl overlay build
